### ISSUE TITLE
Add support for alt attribute

### ISSUE THREAD

**Issue by NickCrews** [Evidlo/markdown_captions#1]
Hi! Thanks for the plugin, I'm finding it helpful.

In vanilla markdown, you could specify both the alt attribute and the title attribute, whereas with this plugin you specify a caption and the title attribute. This means we can't use alt attributes anymore, which is a problem for accessibility. Have you thought about this problem at all? I was thinking of trying to code something up, but I think the syntax would be tricky, because now we would need 3 different bits of metadata (alt, title, and caption) and I'm not sure the best way to fit these into the standard markdown syntax. I wanted to do something that could be used by the entire community.

Thanks!

**Comment by Evidlo** [comment]
Probably discussions about generic directives or block directives will be of interest to you:

https://talk.commonmark.org/t/generic-directives-plugins-syntax/444
https://github.com/commonmark/commonmark-spec/wiki/Generic-Directive-Extension-List
https://talk.commonmark.org/t/block-directives/802

The idea is to have a consistent syntax across all plugins.  So you might have something like

    :caption[http://example.com/foo.png]{title="Title" alt="Alt Text" caption="Foobar"}

**Comment by NickCrews** [comment]
I see, that makes sense. But it looks like Python-Markdown (and therefore this extension) will not migrate to this syntax (source: https://github.com/Python-Markdown/markdown/issues/338#issuecomment-54697337), so this extension won't be able to use it either. It looks like I will have to fork something one-off.

Currently I can use the syntax of
`![Foobar](http://example.com/foo.png "Title"){alt="Alt Text"}`
and the img gets the title attribute correctly, but then the alt attribute is added to the figure element.
What would you think if I tweaked the attribute list parsing at https://github.com/Evidlo/markdown_captions/blob/8bb46cc5954060f6ccddd2ea4a1e5b1e1660e08f/markdown_captions/markdown_captions.py#L38-L45 so that the "alt" attribute was added to the img element instead of the figure element? It would mess up if anyone actually wanted to add an alt attribute to the figure element, but it seems to me like that wouldn't happen.

**Comment by Evidlo** [comment]
I just created an `alt` branch that applies all attributes to the `<img>` instead of `<figure>`.  Hopefully nobody needs their attributes on `<figure>`.

Let me know what you think.
