### ISSUE TITLE
Add support for reference image and short reference image

### ISSUE THREAD

**Issue by fabala** [Evidlo/markdown_captions#3]
Hi,

First of all, thank you for this useful plugin :relaxed: 

Based on https://github.com/Python-Markdown/markdown/pull/994, it would be interesting to support reference image and short reference image, i.e. with patterns like:

```
![caption][ref_url]

![short_ref_caption]

[ref_url]: http://foo.bar
[short_ref_caption]: http://john.doe
```

I tried to analyze the plugin code and I was wondering if the correct solution would be to duplicate the content of the plugin's ImageInlineProcessor class and create new ones inherited from Python-Markdown's ImageReferenceInlineProcessor and  ShortImageReferenceInlineProcessor classes (as you do for your ImageInlineProcessor custom class)?

**Comment by Evidlo** [comment]
This should be fixed with 2.1.1.  Let me know what you think.
