### ISSUE TITLE
Replace depricated markdown.util.etree

### ISSUE THREAD

**Issue by lord-vesel** [Evidlo/markdown_captions#7]
https://github.com/Python-Markdown/markdown/blob/77fb7f1b51076becff488a9b42ef2883153262a0/docs/change_log/release-3.4.md#previously-deprecated-objects-have-been-removed

After markdown's removal deprecated objects, markdown_captions is not usable:

`ImportError: cannot import name 'etree' from 'markdown.util' (/usr/local/lib/python3.10/site-packages/markdown/util.py)`

**Comment by Evidlo** [comment]
Should be fixed with 2.1.2
